"""add messages table

Revision ID: 0a75c58e7b87
Revises: 843cd17611fe
Create Date: 2026-08-25 21:29:04.088183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a75c58e7b87'
down_revision = '843cd17611fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='message_direction'), nullable=False),
    sa.Column('donor_name', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=15), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('message')
    # ### end Alembic commands ###
