"""add table name

Revision ID: 391002d48558
Revises: b972104dd4b5
Create Date: 2026-08-29 23:40:12.218678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '391002d48558'
down_revision = 'b972104dd4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='message_direction'), nullable=False),
        sa.Column('donor_name', sa.String(length=20), nullable=False),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('original_language', sa.String(length=15), nullable=False),
        sa.Column('translated_text', sa.Text(), nullable=True),
        sa.Column('target_language', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('message')  # removed — table was already cleaned up manually
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', postgresql.ENUM('OUTBOUND', 'INBOUND', name='message_direction'), autoincrement=False, nullable=False),
    sa.Column('donor_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_language', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('message_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_pkey'))
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
