"""add campaigns table

Revision ID: 843cd17611fe
Revises: 
Create Date: 2026-08-25 17:22:05.586031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843cd17611fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('goal_amt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('def_lang', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
