"""widen description column

Revision ID: b972104dd4b5
Revises: 0a75c58e7b87
Create Date: 2026-08-29 22:51:35.771584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b972104dd4b5'
down_revision = '0a75c58e7b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('def_lang',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('def_lang',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
